language: node_js
node_js:
  - 10
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - npm run build
  - lhci autorun --upload.target=temporary-public-storage --budgets-file=budgets.json
addons:
  chrome: stable
